spring.datasource.url=jdbc:mysql://localhost:3306/farmer_retailer_new_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}


razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}